/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/albums/{album_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Album Detail */
        get: operations["album_detail_api_v1_albums__album_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums/{album_id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Album Tracks */
        get: operations["album_tracks_api_v1_albums__album_id__tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artists/{artist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artist Detail */
        get: operations["artist_detail_api_v1_artists__artist_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artists/{artist_id}/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artist Albums */
        get: operations["artist_albums_api_v1_artists__artist_id__albums_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artists/{artist_id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artist Tracks */
        get: operations["artist_tracks_api_v1_artists__artist_id__tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Albums */
        get: operations["albums_api_v1_library_albums_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artists */
        get: operations["artists_api_v1_library_artists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/artists/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enrich Artist Artwork */
        post: operations["enrich_artist_artwork_api_v1_library_artists_enrich_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Playlists */
        get: operations["playlists_api_v1_library_playlists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Library */
        get: operations["search_library_api_v1_library_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Library Summary */
        get: operations["library_summary_api_v1_library_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tracks */
        get: operations["tracks_api_v1_library_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/music-connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_api_v1_music_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/music-connections/netease/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Netease Capabilities */
        get: operations["netease_capabilities_api_v1_music_connections_netease_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/music-connections/netease/qr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Netease Qr */
        post: operations["create_netease_qr_api_v1_music_connections_netease_qr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/music-connections/netease/qr/{challenge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll Netease Qr */
        get: operations["poll_netease_qr_api_v1_music_connections_netease_qr__challenge_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/music-connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect */
        delete: operations["disconnect_api_v1_music_connections__connection_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/music-connections/{connection_id}/saved-albums/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synchronize Saved Albums */
        post: operations["synchronize_saved_albums_api_v1_music_connections__connection_id__saved_albums_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/music-connections/{connection_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Synchronization State */
        get: operations["synchronization_state_api_v1_music_connections__connection_id__sync_get"];
        put?: never;
        /** Synchronize */
        post: operations["synchronize_api_v1_music_connections__connection_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/playlists/{playlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Playlist Detail */
        get: operations["playlist_detail_api_v1_playlists__playlist_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/playlists/{playlist_id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Playlist Tracks */
        get: operations["playlist_tracks_api_v1_playlists__playlist_id__tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product Status */
        get: operations["product_status_api_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studio/artifacts/{artifact_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Artifact */
        get: operations["stream_studio_artifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studio/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Asset */
        post: operations["upload_asset_api_v1_studio_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studio/assets/{asset_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Job */
        post: operations["start_job_api_v1_studio_assets__asset_id__jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studio/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_api_v1_studio_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studio/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Detail */
        get: operations["job_detail_api_v1_studio_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studio/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Cancellation */
        post: operations["request_cancellation_api_v1_studio_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studio/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_v1_studio_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studio/jobs/{job_id}/waveform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Waveform */
        get: operations["waveform_api_v1_studio_jobs__job_id__waveform_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studio/tracks/{track_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Library Track Job
         * @description Import playable account audio locally, then queue a normal Studio job.
         */
        post: operations["start_library_track_job_api_v1_studio_tracks__track_id__jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track Detail */
        get: operations["track_detail_api_v1_tracks__track_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks/{track_id}/playback-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Playback Source */
        post: operations["playback_source_api_v1_tracks__track_id__playback_source_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks/{track_id}/stem-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stem Entry */
        post: operations["stem_entry_api_v1_tracks__track_id__stem_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Database Health */
        get: operations["database_health_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlbumDetail */
        AlbumDetail: {
            /** Artists */
            artists?: components["schemas"]["EntityReference"][];
            /** Artwork Url */
            artwork_url?: string | null;
            /** Id */
            id: string;
            /** Library Track Count */
            library_track_count: number;
            /** Title */
            title: string;
        };
        /** AlbumItem */
        AlbumItem: {
            /** Artists */
            artists?: components["schemas"]["EntityReference"][];
            /** Artwork Url */
            artwork_url?: string | null;
            /** Id */
            id: string;
            /**
             * Sort Group
             * @default #
             */
            sort_group: string;
            /** Title */
            title: string;
        };
        /** AlbumPage */
        AlbumPage: {
            /** Group */
            group?: string | null;
            /** Groups */
            groups?: components["schemas"]["AlphabetGroup"][];
            /** Items */
            items: components["schemas"]["AlbumItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Previous Cursor */
            previous_cursor?: string | null;
            /**
             * Range End
             * @default 0
             */
            range_end: number;
            /**
             * Range Start
             * @default 0
             */
            range_start: number;
            /**
             * Sort
             * @default asc
             * @enum {string}
             */
            sort: "asc" | "desc";
            /** Total */
            total: number;
        };
        /** AlphabetGroup */
        AlphabetGroup: {
            /** Count */
            count: number;
            /** Key */
            key: string;
        };
        /** ArtistDetail */
        ArtistDetail: {
            /** Artwork Url */
            artwork_url?: string | null;
            /** Id */
            id: string;
            /** Library Track Count */
            library_track_count: number;
            /** Name */
            name: string;
            /** Represented Album Count */
            represented_album_count: number;
        };
        /** ArtistEnrichmentResponse */
        ArtistEnrichmentResponse: {
            /** Artists With Artwork */
            artists_with_artwork: number;
            /** Attempted */
            attempted: number;
            /** Duration Ms */
            duration_ms: number;
            /** Enriched */
            enriched: number;
            /** Failures */
            failures: number;
            /** Total Artists */
            total_artists: number;
            /** Unavailable Artwork */
            unavailable_artwork: number;
        };
        /** ArtistItem */
        ArtistItem: {
            /** Artwork Url */
            artwork_url?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Sort Group
             * @default #
             */
            sort_group: string;
        };
        /** ArtistPage */
        ArtistPage: {
            /** Group */
            group?: string | null;
            /** Groups */
            groups?: components["schemas"]["AlphabetGroup"][];
            /** Items */
            items: components["schemas"]["ArtistItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Previous Cursor */
            previous_cursor?: string | null;
            /**
             * Range End
             * @default 0
             */
            range_end: number;
            /**
             * Range Start
             * @default 0
             */
            range_start: number;
            /**
             * Sort
             * @default asc
             * @enum {string}
             */
            sort: "asc" | "desc";
            /** Total */
            total: number;
        };
        /** Body_upload_asset_api_v1_studio_assets_post */
        Body_upload_asset_api_v1_studio_assets_post: {
            /**
             * File
             * @description Local MP3, WAV, FLAC, or M4A/AAC audio
             */
            file: string;
        };
        /** ConnectionList */
        ConnectionList: {
            /** Items */
            items?: components["schemas"]["ConnectionSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * ConnectionStatus
         * @enum {string}
         */
        ConnectionStatus: "IDLE" | "CREATING_QR" | "WAITING_SCAN" | "WAITING_CONFIRM" | "CONNECTED" | "EXPIRED" | "FAILED" | "DISCONNECTED";
        /** ConnectionSummary */
        ConnectionSummary: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Id */
            id: string;
            /** Nickname */
            nickname?: string | null;
            /** Provider */
            provider: string;
            /** Provider User Id */
            provider_user_id?: string | null;
            /** Status */
            status: string;
        };
        /** EntityReference */
        EntityReference: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Database */
            database?: string | null;
            /** Release */
            release?: string | null;
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        /** LibraryCounts */
        LibraryCounts: {
            /**
             * Albums
             * @default 0
             */
            albums: number;
            /**
             * Artists
             * @default 0
             */
            artists: number;
            /**
             * Playlists
             * @default 0
             */
            playlists: number;
            /**
             * Tracks
             * @default 0
             */
            tracks: number;
        };
        /** LibrarySearchResponse */
        LibrarySearchResponse: {
            /** Albums */
            albums?: components["schemas"]["SearchAlbumResult"][];
            /** Artists */
            artists?: components["schemas"]["SearchArtistResult"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Playlists */
            playlists?: components["schemas"]["SearchPlaylistResult"][];
            /** Previous Cursor */
            previous_cursor?: string | null;
            /** Query */
            query: string;
            /**
             * Range End
             * @default 0
             */
            range_end: number;
            /**
             * Range Start
             * @default 0
             */
            range_start: number;
            /** Total */
            total: number;
            /** Tracks */
            tracks?: components["schemas"]["SearchTrackResult"][];
        };
        /** LibrarySummary */
        LibrarySummary: {
            /**
             * Connection State
             * @enum {string}
             */
            connection_state: "not_connected" | "connected";
            counts: components["schemas"]["LibraryCounts"];
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Sync State */
            sync_state: string;
        };
        /** NeteaseCapabilities */
        NeteaseCapabilities: {
            /** Auth States */
            auth_states: string[];
            current_state: components["schemas"]["ConnectionStatus"];
            /**
             * Implementation Stage
             * @constant
             */
            implementation_stage: "implemented";
            /** Message */
            message: string;
            /**
             * Provider
             * @constant
             */
            provider: "netease";
            /**
             * Real World Verified
             * @default false
             */
            real_world_verified: boolean;
        };
        /** OperationResponse */
        OperationResponse: {
            /** Status */
            status: string;
        };
        /** PlaybackSourceResponse */
        PlaybackSourceResponse: {
            /** Duration Ms */
            duration_ms?: number | null;
            /** Expires At */
            expires_at?: string | null;
            /** Mime Type */
            mime_type: string;
            /**
             * Provider
             * @default netease
             * @constant
             */
            provider: "netease";
            /** Quality */
            quality?: string | null;
            /** Resolution Ms */
            resolution_ms: number;
            /**
             * Source Type
             * @default provider_stream
             * @constant
             */
            source_type: "provider_stream";
            /** Track Id */
            track_id?: string | null;
            /** Url */
            url: string;
        };
        /** PlaylistDetail */
        PlaylistDetail: {
            /** Artwork Url */
            artwork_url?: string | null;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Provider Track Count */
            provider_track_count?: number | null;
            /** Synchronized Track Count */
            synchronized_track_count: number;
        };
        /** PlaylistItem */
        PlaylistItem: {
            /** Artwork Url */
            artwork_url?: string | null;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Sort Group
             * @default #
             */
            sort_group: string;
            /** Track Count */
            track_count?: number | null;
        };
        /** PlaylistPage */
        PlaylistPage: {
            /** Group */
            group?: string | null;
            /** Groups */
            groups?: components["schemas"]["AlphabetGroup"][];
            /** Items */
            items: components["schemas"]["PlaylistItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Previous Cursor */
            previous_cursor?: string | null;
            /**
             * Range End
             * @default 0
             */
            range_end: number;
            /**
             * Range Start
             * @default 0
             */
            range_start: number;
            /**
             * Sort
             * @default asc
             * @enum {string}
             */
            sort: "asc" | "desc";
            /** Total */
            total: number;
        };
        /** ProductStatus */
        ProductStatus: {
            /** Capabilities */
            capabilities: {
                [key: string]: "implemented" | "verification_pending" | "designed";
            };
            /**
             * Release
             * @enum {string}
             */
            release: "R0" | "R1" | "R2.1" | "R2" | "R3" | "R4.1";
            /**
             * Stage
             * @enum {string}
             */
            stage: "architecture_and_greenfield_bootstrap" | "netease_integration_verification" | "library_experience_and_playback" | "personal_music_intelligence" | "live_concert_intelligence" | "production_audio_studio";
        };
        /** QrChallengeResponse */
        QrChallengeResponse: {
            /** Challenge Id */
            challenge_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Qr Image Data Url */
            qr_image_data_url: string;
            /** Qr Url */
            qr_url: string;
            /** Status */
            status: string;
        };
        /** QrStatusResponse */
        QrStatusResponse: {
            /** Challenge Id */
            challenge_id: string;
            connection?: components["schemas"]["ConnectionSummary"] | null;
            /** Status */
            status: string;
        };
        /** SavedAlbumSyncResponse */
        SavedAlbumSyncResponse: {
            /** Albums */
            albums: number;
            /** Status */
            status: string;
        };
        /** SearchAlbumResult */
        SearchAlbumResult: {
            album: components["schemas"]["AlbumItem"];
            /**
             * Entity Type
             * @default album
             * @constant
             */
            entity_type: "album";
            /**
             * Match
             * @enum {string}
             */
            match: "exact" | "prefix" | "substring";
        };
        /** SearchArtistResult */
        SearchArtistResult: {
            artist: components["schemas"]["ArtistItem"];
            /**
             * Entity Type
             * @default artist
             * @constant
             */
            entity_type: "artist";
            /** Library Track Count */
            library_track_count: number;
            /**
             * Match
             * @enum {string}
             */
            match: "exact" | "prefix" | "substring";
        };
        /** SearchPlaylistResult */
        SearchPlaylistResult: {
            /**
             * Entity Type
             * @default playlist
             * @constant
             */
            entity_type: "playlist";
            /**
             * Match
             * @enum {string}
             */
            match: "exact" | "prefix" | "substring";
            playlist: components["schemas"]["PlaylistItem"];
        };
        /** SearchTrackResult */
        SearchTrackResult: {
            /**
             * Entity Type
             * @default track
             * @constant
             */
            entity_type: "track";
            /**
             * Match
             * @enum {string}
             */
            match: "exact" | "prefix" | "substring";
            track: components["schemas"]["TrackItem"];
        };
        /** StemEntryResponse */
        StemEntryResponse: {
            /** Message */
            message: string;
            /**
             * Status
             * @constant
             */
            status: "ACCOUNT_SONG_SELECTED";
            /** Studio Url */
            studio_url: string;
        };
        /** StudioArtifactResponse */
        StudioArtifactResponse: {
            /** Channels */
            channels: number;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Id */
            id: string;
            /**
             * Media Type
             * @default audio/flac
             * @constant
             */
            media_type: "audio/flac";
            /** Sample Rate */
            sample_rate: number;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Stem Type
             * @enum {string}
             */
            stem_type: "VOCALS" | "DRUMS" | "BASS" | "GUITAR" | "PIANO" | "OTHER";
            /** Stream Url */
            stream_url: string;
        };
        /** StudioAssetResponse */
        StudioAssetResponse: {
            /** Channels */
            channels: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Id */
            id: string;
            /** Media Type */
            media_type: string;
            /** Original Filename */
            original_filename: string;
            /**
             * Reused
             * @default false
             */
            reused: boolean;
            /** Sample Rate */
            sample_rate: number;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** StudioJobListResponse */
        StudioJobListResponse: {
            /** Items */
            items?: components["schemas"]["StudioJobResponse"][];
        };
        /** StudioJobResponse */
        StudioJobResponse: {
            /** Artifacts */
            artifacts?: components["schemas"]["StudioArtifactResponse"][];
            asset: components["schemas"]["StudioAssetResponse"];
            /** Attempt Count */
            attempt_count: number;
            /**
             * Cancellable
             * @default false
             */
            cancellable: boolean;
            /** Completed At */
            completed_at?: string | null;
            /** Configuration */
            configuration?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Demucs Version */
            demucs_version?: string | null;
            /** Device */
            device?: string | null;
            /** Id */
            id: string;
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version?: string | null;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /**
             * Reused
             * @default false
             */
            reused: boolean;
            /** Safe Error Code */
            safe_error_code?: string | null;
            /** Safe Error Message */
            safe_error_message?: string | null;
            /** Source Track Ids */
            source_track_ids?: string[];
            /** Stage */
            stage: string;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "QUEUED" | "PREPARING" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
            /** Waveform Url */
            waveform_url?: string | null;
        };
        /** SyncResponse */
        SyncResponse: {
            /** Albums */
            albums: number;
            /** Artists */
            artists: number;
            /** Artwork Count */
            artwork_count: number;
            /** Partial Failures */
            partial_failures: number;
            /** Playlists */
            playlists: number;
            /** Status */
            status: string;
            /** Timings Ms */
            timings_ms: {
                [key: string]: number;
            };
            /** Track Memberships */
            track_memberships: number;
            /** Tracks */
            tracks: number;
        };
        /** SyncStateResponse */
        SyncStateResponse: {
            /** Checkpoint */
            checkpoint?: {
                [key: string]: unknown;
            };
            /** Processed Items */
            processed_items: number;
            /** Safe Error */
            safe_error?: string | null;
            /** Status */
            status: string;
            /** Total Items */
            total_items?: number | null;
        };
        /** TrackDetail */
        TrackDetail: {
            album?: components["schemas"]["EntityReference"] | null;
            /** Artists */
            artists?: components["schemas"]["EntityReference"][];
            /** Artwork Url */
            artwork_url?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Id */
            id: string;
            /** Playlists */
            playlists?: components["schemas"]["EntityReference"][];
            /** Title */
            title: string;
        };
        /** TrackItem */
        TrackItem: {
            /** Album */
            album?: string | null;
            /** Album Id */
            album_id?: string | null;
            /** Artist Items */
            artist_items?: components["schemas"]["EntityReference"][];
            /** Artists */
            artists?: string[];
            /** Artwork Url */
            artwork_url?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Id */
            id: string;
            /** Playlist Position */
            playlist_position?: number | null;
            /**
             * Sort Group
             * @default #
             */
            sort_group: string;
            /** Title */
            title: string;
        };
        /** TrackPage */
        TrackPage: {
            /** Group */
            group?: string | null;
            /** Groups */
            groups?: components["schemas"]["AlphabetGroup"][];
            /** Items */
            items: components["schemas"]["TrackItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Previous Cursor */
            previous_cursor?: string | null;
            /**
             * Range End
             * @default 0
             */
            range_end: number;
            /**
             * Range Start
             * @default 0
             */
            range_start: number;
            /**
             * Sort
             * @default asc
             * @enum {string}
             */
            sort: "asc" | "desc" | "original";
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    album_detail_api_v1_albums__album_id__get: {
        parameters: {
            query?: {
                scope?: "liked" | "personal" | "all";
            };
            header?: never;
            path: {
                album_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    album_tracks_api_v1_albums__album_id__tracks_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                sort?: "asc" | "desc";
                scope?: "liked" | "personal" | "all";
            };
            header?: never;
            path: {
                album_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artist_detail_api_v1_artists__artist_id__get: {
        parameters: {
            query?: {
                scope?: "liked" | "personal" | "all";
            };
            header?: never;
            path: {
                artist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artist_albums_api_v1_artists__artist_id__albums_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                sort?: "asc" | "desc";
                scope?: "liked" | "personal" | "all";
            };
            header?: never;
            path: {
                artist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artist_tracks_api_v1_artists__artist_id__tracks_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                sort?: "asc" | "desc";
                scope?: "liked" | "personal" | "all";
            };
            header?: never;
            path: {
                artist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    albums_api_v1_library_albums_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                sort?: "asc" | "desc";
                group?: string | null;
                scope?: "liked" | "personal" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artists_api_v1_library_artists_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                sort?: "asc" | "desc";
                group?: string | null;
                scope?: "liked" | "personal" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enrich_artist_artwork_api_v1_library_artists_enrich_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistEnrichmentResponse"];
                };
            };
        };
    };
    playlists_api_v1_library_playlists_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                sort?: "asc" | "desc";
                group?: string | null;
                scope?: "liked" | "personal" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_library_api_v1_library_search_get: {
        parameters: {
            query: {
                q: string;
                /** @description Comma-separated track,artist,album,playlist */
                types?: string | null;
                cursor?: string | null;
                limit?: number;
                scope?: "liked" | "personal" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibrarySearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    library_summary_api_v1_library_summary_get: {
        parameters: {
            query?: {
                scope?: "liked" | "personal" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibrarySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tracks_api_v1_library_tracks_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                sort?: "asc" | "desc";
                group?: string | null;
                scope?: "liked" | "personal" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connections_api_v1_music_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionList"];
                };
            };
        };
    };
    netease_capabilities_api_v1_music_connections_netease_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeteaseCapabilities"];
                };
            };
        };
    };
    create_netease_qr_api_v1_music_connections_netease_qr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QrChallengeResponse"];
                };
            };
        };
    };
    poll_netease_qr_api_v1_music_connections_netease_qr__challenge_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QrStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_api_v1_music_connections__connection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    synchronize_saved_albums_api_v1_music_connections__connection_id__saved_albums_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedAlbumSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    synchronization_state_api_v1_music_connections__connection_id__sync_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    synchronize_api_v1_music_connections__connection_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    playlist_detail_api_v1_playlists__playlist_id__get: {
        parameters: {
            query?: {
                scope?: "liked" | "personal" | "all";
            };
            header?: never;
            path: {
                playlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    playlist_tracks_api_v1_playlists__playlist_id__tracks_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                sort?: "original" | "asc" | "desc";
                scope?: "liked" | "personal" | "all";
            };
            header?: never;
            path: {
                playlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_status_api_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductStatus"];
                };
            };
        };
    };
    stream_studio_artifact: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: {
                "if-none-match"?: string | null;
                "x-musicscope-user-id"?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_asset_api_v1_studio_assets_post: {
        parameters: {
            query?: never;
            header?: {
                "x-musicscope-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_asset_api_v1_studio_assets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioAssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_job_api_v1_studio_assets__asset_id__jobs_post: {
        parameters: {
            query?: {
                model?: string;
                track_id?: string | null;
            };
            header?: {
                "x-musicscope-user-id"?: string | null;
            };
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_api_v1_studio_jobs_get: {
        parameters: {
            query?: never;
            header?: {
                "x-musicscope-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioJobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_detail_api_v1_studio_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-musicscope-user-id"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_cancellation_api_v1_studio_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "x-musicscope-user-id"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_v1_studio_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                "x-musicscope-user-id"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    waveform_api_v1_studio_jobs__job_id__waveform_get: {
        parameters: {
            query?: never;
            header?: {
                "x-musicscope-user-id"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_library_track_job_api_v1_studio_tracks__track_id__jobs_post: {
        parameters: {
            query?: {
                model?: string;
            };
            header?: {
                "x-musicscope-user-id"?: string | null;
            };
            path: {
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_detail_api_v1_tracks__track_id__get: {
        parameters: {
            query?: {
                scope?: "liked" | "personal" | "all";
            };
            header?: never;
            path: {
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    playback_source_api_v1_tracks__track_id__playback_source_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybackSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stem_entry_api_v1_tracks__track_id__stem_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StemEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    database_health_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
